name: test
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - libgcc=15.2.0=he0feb66_18
  - libgcc-ng=15.2.0=h69a702a_18
  - libgomp=15.2.0=he0feb66_18
  - ncurses=6.5=h2d0b736_3
  - readline=7.0=hf8c457e_1001
prefix: /home/mgchoi/.conda/envs/test
